# Generated by Django 4.1.13 on 2024-11-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='13.jpeg', upload_to='profile_images/'),
        ),
    ]
